"""Add initial database models

Revision ID: 015b3b553818
Revises: 
Create Date: 2025-04-19 12:42:07.948607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015b3b553818'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('hub_type', sa.Enum('MAIN', 'MICRO', 'DROP_OFF', 'MOBILE', name='hubtype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hub', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hub_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_hub_longitude'), ['longitude'], unique=False)

    op.create_table('recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('has_kitchen', sa.Boolean(), nullable=True),
    sa.Column('recipient_type', sa.Enum('HOUSEHOLD', 'HOMELESS', 'TEMPORARY', name='recipienttype'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipient_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipient_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipient_nickname'), ['nickname'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_user_id', sa.Integer(), nullable=True),
    sa.Column('donor_name', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('hub_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ASSIGNED', 'DELIVERED', name='donationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['hub_id'], ['hub.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donation_donor_user_id'), ['donor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_donation_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_donation_status'), ['status'], unique=False)

    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('volunteer_role', sa.Enum('DRIVER', 'REPORTER', 'COORDINATOR', name='volunteerrole'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_volunteer_role'), ['volunteer_role'], unique=False)

    op.create_table('delivery_route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.Column('hub_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'DONE', 'CANCELLED', name='routestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hub_id'], ['hub.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_route', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_route_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_route_volunteer_id'), ['volunteer_id'], unique=False)

    op.create_table('volunteer_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipient.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volunteer_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_report_timestamp'), ['timestamp'], unique=False)

    op.create_table('delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'DELIVERED', 'FAILED', name='deliverystatus'), nullable=False),
    sa.Column('confirmation_image', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donation.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipient.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['delivery_route.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('donation_id')
    )
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_status'))

    op.drop_table('delivery')
    with op.batch_alter_table('volunteer_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_report_timestamp'))

    op.drop_table('volunteer_report')
    with op.batch_alter_table('delivery_route', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_route_volunteer_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_route_status'))

    op.drop_table('delivery_route')
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_volunteer_role'))

    op.drop_table('volunteer')
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donation_status'))
        batch_op.drop_index(batch_op.f('ix_donation_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_donation_donor_user_id'))

    op.drop_table('donation')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipient_nickname'))
        batch_op.drop_index(batch_op.f('ix_recipient_longitude'))
        batch_op.drop_index(batch_op.f('ix_recipient_latitude'))

    op.drop_table('recipient')
    with op.batch_alter_table('hub', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hub_longitude'))
        batch_op.drop_index(batch_op.f('ix_hub_latitude'))

    op.drop_table('hub')
    # ### end Alembic commands ###
